FROM python:3.11-slim

WORKDIR /app

COPY make/requirements.txt /app/
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY streamlit/ /app/

EXPOSE 8501

CMD ["streamlit", "run", "app.py"]
